package com.example.aichat.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_light_primary = Color(0xFF00696D)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF6FF6FE)
val md_light_onPrimaryContainer = Color(0xFF002021)
val md_light_secondary = Color(0xFF4A6363)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFCCE8E7)
val md_light_onSecondaryContainer = Color(0xFF041F1F)
val md_light_tertiary = Color(0xFF4B607C)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFD3E4FF)
val md_light_onTertiaryContainer = Color(0xFF041C35)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFAFDFC)
val md_light_onBackground = Color(0xFF191C1C)
val md_light_surface = Color(0xFFFAFDFC)
val md_light_onSurface = Color(0xFF191C1C)
val md_light_surfaceVariant = Color(0xFFDAE5E3)
val md_light_onSurfaceVariant = Color(0xFF3F4947)
val md_light_outline = Color(0xFF6F7978)

// Dark theme colors
val md_dark_primary = Color(0xFF4CD9E2)
val md_dark_onPrimary = Color(0xFF00373A)
val md_dark_primaryContainer = Color(0xFF004F53)
val md_dark_onPrimaryContainer = Color(0xFF6FF6FE)
val md_dark_secondary = Color(0xFFB0CCCB)
val md_dark_onSecondary = Color(0xFF1B3534)
val md_dark_secondaryContainer = Color(0xFF324B4B)
val md_dark_onSecondaryContainer = Color(0xFFCCE8E7)
val md_dark_tertiary = Color(0xFFB3C8E8)
val md_dark_onTertiary = Color(0xFF1C314B)
val md_dark_tertiaryContainer = Color(0xFF334863)
val md_dark_onTertiaryContainer = Color(0xFFD3E4FF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF191C1C)
val md_dark_onBackground = Color(0xFFE0E3E2)
val md_dark_surface = Color(0xFF191C1C)
val md_dark_onSurface = Color(0xFFE0E3E2)
val md_dark_surfaceVariant = Color(0xFF3F4947)
val md_dark_onSurfaceVariant = Color(0xFFBEC9C6)
val md_dark_outline = Color(0xFF899390)
